"""Initial schema

Revision ID: 5bc442a70e3b
Revises:
Create Date: 2026-03-07 22:06:37.460888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bc442a70e3b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("vehicle_id", sa.String(length=50), nullable=False),
        sa.Column("vehicle_type", sa.String(length=50), nullable=False),
        sa.Column(
            "registration_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vehicle_id", sa.String(length=50), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telemetry_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alerts_detected_at",
        "alerts",
        ["detected_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_alerts_severity",
        "alerts",
        ["severity"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_alerts_status",
        "alerts",
        ["status"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_alerts_vehicle_id",
        "alerts",
        ["vehicle_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vehicle_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("engine_temp", sa.Float(), nullable=True),
        sa.Column("oil_pressure", sa.Float(), nullable=True),
        sa.Column("battery_voltage", sa.Float(), nullable=True),
        sa.Column("fuel_level", sa.Float(), nullable=True),
        sa.Column("tire_pressure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rpm", sa.Float(), nullable=True),
        sa.Column("throttle_position", sa.Float(), nullable=True),
        sa.Column("brake_status", sa.Boolean(), nullable=True),
        sa.Column("odometer", sa.Float(), nullable=True),
        sa.Column("vibration_x", sa.Float(), nullable=True),
        sa.Column("vibration_y", sa.Float(), nullable=True),
        sa.Column("vibration_z", sa.Float(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle_id"],
        ),
        sa.PrimaryKeyConstraint("id", "vehicle_id", "timestamp"),
    )
    op.create_index(
        "idx_telemetry_timestamp",
        "telemetry",
        ["timestamp"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_telemetry_vehicle_timestamp",
        "telemetry",
        ["vehicle_id", "timestamp"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_telemetry_vehicle_timestamp",
        table_name="telemetry",
        postgresql_using="btree",
    )
    op.drop_index("idx_telemetry_timestamp", table_name="telemetry", postgresql_using="btree")
    op.drop_table("telemetry")
    op.drop_index("idx_alerts_vehicle_id", table_name="alerts", postgresql_using="btree")
    op.drop_index("idx_alerts_status", table_name="alerts", postgresql_using="btree")
    op.drop_index("idx_alerts_severity", table_name="alerts", postgresql_using="btree")
    op.drop_index("idx_alerts_detected_at", table_name="alerts", postgresql_using="btree")
    op.drop_table("alerts")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
